### ISSUE TITLE
Question about the test metrics of imputation task

### ISSUE THREAD

**Issue by MartinZoey** [OmicsML/scDiff#2]
I find that there are three test metrics relative to correlation of imputation: denoise_corr_normed│  denoise_corr_normed_all │ denoise_global_corr_normed. 
I wonder what are their differences? And what's the meaning of 'global'? Thanks a lot!

**Comment by WenzhuoTang** [comment]
Hi @MartinZoey, thank you for your interest in our work. All three metrics are the mean of Pearson correlations of cells between imputed and ground truth, with different coverage on the entries of gene expression. Here is an illustration figure.
 
![imputation_metrics](https://github.com/OmicsML/scDiff/assets/103127957/481166d5-a74c-4b7b-8c46-42dd1eddcd78)

The denoise_corr_normed_all is calculated on all the entries, the denoise_corr_normed is calculated only on the entries that are masked during training, and the denoise_global_corr_normed first flattens the masked entries and then calculates the correlation. Just note that the word `normed` means we are using normalized counts. In our paper, we chose denoise_corr_normed as the default metric.

**Comment by MartinZoey** [comment]
> Hi @MartinZoey, thank you for your interest in our work. All three metrics are the mean of Pearson correlations of cells between imputed and ground truth, with different coverage on the entries of gene expression. Here is an illustration figure.
> 
> ![imputation_metrics](https://private-user-images.githubusercontent.com/103127957/305224183-481166d5-a74c-4b7b-8c46-42dd1eddcd78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NzkxMzcsIm5iZiI6MTcwODY3ODgzNywicGF0aCI6Ii8xMDMxMjc5NTcvMzA1MjI0MTgzLTQ4MTE2NmQ1LWE3NGMtNGI3Yi04YzQ2LTQyZGQxZWRkY2Q3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QwOTAwMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGYxOGViZDA5NjliNTMwMGVlYjYxZTcwNjU3YTkwOGNkYTM2YWViOTAxZjU0ZWY3NzYwYmQ3MGM3MmFmYjg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NIg2580HbDw70gO124SefuYYUS8FNhFTZ1MZ7MEl00w)
> 
> The _denoise_corr_normed_all_ is calculated on all the entries, the _denoise_corr_normed_ is calculated only on the entries that are masked during training, and the _denoise_global_corr_normed_ first flattens the masked entries and then calculates the correlation. Just note that the word `normed` means we are using normalized counts. In our paper, we chose denoise_corr_normed as the default metric.

Thank you so much for your detailed and clear explanation. It really helps a lot!
