### ISSUE TITLE
Enquiry about the data process

### ISSUE THREAD

**Issue by EddieBio** [OmicsML/scDiff#4]
Hi,

May I know how the authors process the data? For example, how do you normalize the data?

Thank you very much for your help.

**Comment by WenzhuoTang** [comment]
Hi @EddieBio , thank you for your interest in our work. For all the datasets, we applied the standard preprocessing pipeline: filtering out all-zero genes and cells, library size normalization with $\text{target sum} = 10000$, and then log1p normalization.
